#!/usr/bin/env bash

## Copyright (C) 2020-2025 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Hyprland

WALLPAPER='/home/jlight/.config/hypr/wallpapers/wallpaper.png'

swaybg --output '*' --mode fill --image "$WALLPAPER"
